"""initial schema

Revision ID: 0480b9bdd9b5
Revises: 
Create Date: 2026-06-04 20:07:18.056758
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0480b9bdd9b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automod_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automod_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automod_rules_guild_id'), ['guild_id'], unique=False)

    op.create_table('command_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.String(length=64), nullable=False),
    sa.Column('allowed_role_ids', sa.JSON(), nullable=False),
    sa.Column('allowed_user_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'command', name='uq_cmdperm_guild_command')
    )
    with op.batch_alter_table('command_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_permissions_guild_id'), ['guild_id'], unique=False)

    op.create_table('dashboard_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('embeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('footer', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeds_guild_id'), ['guild_id'], unique=False)

    op.create_table('flagged_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_flagged_guild_user')
    )
    with op.batch_alter_table('flagged_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flagged_users_guild_id'), ['guild_id'], unique=False)

    op.create_table('forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('submit_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forms_guild_id'), ['guild_id'], unique=False)

    op.create_table('global_bans',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_group_guild_name')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_guild_id'), ['guild_id'], unique=False)

    op.create_table('guild_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('welcome_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('goodbye_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('goodbye_message', sa.Text(), nullable=True),
    sa.Column('autorole_ids', sa.JSON(), nullable=False),
    sa.Column('log_category_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('mod_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('target_tag', sa.String(length=64), nullable=True),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_tag', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mod_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mod_actions_guild_id'), ['guild_id'], unique=False)

    op.create_table('reaction_role_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reaction_role_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_role_messages_guild_id'), ['guild_id'], unique=False)

    op.create_table('custom_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('embed_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['embed_id'], ['embeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_custom_cmd_guild_name')
    )
    with op.batch_alter_table('custom_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_commands_guild_id'), ['guild_id'], unique=False)

    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=45), nullable=False),
    sa.Column('style', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_role_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_pk', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=128), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['message_pk'], ['reaction_role_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction_role_entries')
    op.drop_table('group_items')
    op.drop_table('form_submissions')
    op.drop_table('form_fields')
    with op.batch_alter_table('custom_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_commands_guild_id'))

    op.drop_table('custom_commands')
    with op.batch_alter_table('reaction_role_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_role_messages_guild_id'))

    op.drop_table('reaction_role_messages')
    with op.batch_alter_table('mod_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mod_actions_guild_id'))

    op.drop_table('mod_actions')
    op.drop_table('guild_config')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_guild_id'))

    op.drop_table('groups')
    op.drop_table('global_bans')
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forms_guild_id'))

    op.drop_table('forms')
    with op.batch_alter_table('flagged_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flagged_users_guild_id'))

    op.drop_table('flagged_users')
    with op.batch_alter_table('embeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeds_guild_id'))

    op.drop_table('embeds')
    op.drop_table('dashboard_admin')
    with op.batch_alter_table('command_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_permissions_guild_id'))

    op.drop_table('command_permissions')
    with op.batch_alter_table('automod_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automod_rules_guild_id'))

    op.drop_table('automod_rules')
    # ### end Alembic commands ###
